### ISSUE TITLE
Wallet Frozen

### ISSUE THREAD

**Issue by dker4** [mymonero/mymonero-app-js#284]
There is a problem with my wallet. Whenever I try to send monero It just gets stuck "pending" and no transaction shows up in the block. 

Monero Log: 
`[2019-06-09 21:07:40.917] [error] Error: Error: net::ERR_CONNECTION_RESET
    at GitHubProvider.getLatestVersion (C:\Program Files\MyMonero\resources\app.asar\node_modules\electron-updater\src\providers\GitHubProvider.ts:39:25)
    at C:\Program Files\MyMonero\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:347:26
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater.getUpdateInfoAndProvider (C:\Program Files\MyMonero\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:336:43)
    at C:\Program Files\MyMonero\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:363:31
    at Generator.next (<anonymous>)
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Program Files\MyMonero\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:360:34)
    at NsisUpdater.checkForUpdates (C:\Program Files\MyMonero\resources\app.asar\node_modules\electron-updater\src\AppUpdater.ts:220:35)
    at Controller.checkForUpdates (C:\Program Files\MyMonero\resources\app.asar\local_modules\AppUpdates\AppUpdatesController.electron.main.js:301:15)
    at autoCheck (C:\Program Files\MyMonero\resources\app.asar\local_modules\AppUpdates\AppUpdatesController.electron.main.js:231:10)
    at Timeout._onTimeout (C:\Program Files\MyMonero\resources\app.asar\local_modules\AppUpdates\AppUpdatesController.electron.main.js:239:5)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)`

Windows Event Log :
`Faulting application name: MyMonero.exe, version: 1.1.11.0, time stamp: 0x5c476a58
Faulting module name: MyMonero.exe, version: 1.1.11.0, time stamp: 0x5c476a58
Exception code: 0xc0000005
Fault offset: 0x0000000000091455
Faulting process id: 0x105d4
Faulting application start time: 0x01d51d73696fbe61
Faulting application path: C:\Program Files\MyMonero\MyMonero.exe
Faulting module path: C:\Program Files\MyMonero\MyMonero.exe
Report Id: a457d216-6667-4cd0-ba3c-09350f835919
Faulting package full name: 
Faulting package-relative application ID:`

I'm very scared and not sure what to do.

**Comment by paulshapiro** [comment]
Hey there,

It looks like you're hitting a crash in the software updater that comes with Electron.

As long as you have your mnemonic seed, you could try reinstalling the app, or, at least, as a first step which doesn't require deleting your existing data, try it in the web wallet or try installing the app on another OS installation/computer. 

(Funds are safu. For further help, pls contact us at support. I'll keep this ticket open as a bug report)

**Comment by dker4** [comment]
Okay, so I logged into the MyMonero web wallet and see all my recent transactions sitll pending with nothing changed. The same problem still persists. I tried to send a small amount of XMR in the web wallet to see it goes to pending, but NOTHING in the block. So nothing changes.

**Comment by mohsenack** [comment]
Same problem here, tried on another PC and still have this problem, my transaction is still pending and I can’t make any other transaction.

**Comment by paulshapiro** [comment]
Can you email support? It's probably just the daemon falling behind. let me check

**Comment by paulshapiro** [comment]
Please try it again btw

**Comment by paulshapiro** [comment]
(Daemon had gotten stuck)
