### ISSUE TITLE
Choose file error

### ISSUE THREAD

**Issue by ryan-gi** [mymonero/mymonero-app-js#306]
**OS:** macOS
**OS version:** 10.15.6
**app version:** 1.1.13
**app source:** binary downloaded from mymonero.com
**recreating error:** testing "choose file" feature using QR image file generated by the receive section
**Error displayed:**
An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:

TypeError: Assignment to constant variable.

TypeError: Assignment to constant variable.
    at FilesytemUI.PresentDialogToOpenOneImageFile (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/FilesystemUI/FilesystemUI.electron.js:168:10)
    at SendFundsView.__didSelect_actionButton_chooseFile (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/SendFundsTab/Views/SendFundsView_Base.web.js:2157:29)
    at /Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/SendFundsTab/Views/SendFundsView_Base.web.js:641:10
    at HTMLAnchorElement.<anonymous> (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/MMAppUICommonComponents/actionButtons.web.js:209:4)

**Comment by karlbuys** [comment]
Hi @ryan-gi. Apologies for the slow response. 

I have reproduced the issue on my side. I'll work with @devinpearson to resolve this. I'll let you know once we've fixed it and published a fixed release.

Thank you for letting us know.

**Comment by partcyborg** [comment]
What is the status of this?

I encountered this issue as well.  It makes it a lot more difficult to send money using one of these QR codes, as I have to render it with an external app and then manually copy/paste everything
