### ISSUE TITLE
Updater Error - ERR_UPDATER_ZIP_FILE_NOT_FOUND when opening the app

### ISSUE THREAD

**Issue by Bianca2112** [mymonero/mymonero-app-js#316]
Multiple users using both windows and mac are receiving the following error when opening the app:

abort({"code":"ERR_UPDATER_ZIP_FILE_NOT_FOUND"}) at Error

at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11630)

at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11801)

at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:560006)

at process.emit (events.js:203:13)

at processPromiseRejections (internal/process/promises.js:201:33)

at processTicksAndRejections (internal/process/task_queues.js:86:32)

**Comment by Drarok** [comment]
I get this error first:
```
ZIP file not provided: [
  {
    "url": "https://github.com/mymonero/mymonero-app-js/releases/download/v1.1.16-beta/MyMonero-1.1.16-beta.dmg",
    "info": {
      "url": "MyMonero-1.1.16-beta.dmg",
      "sha512": "qeN2bq6AFbJ9IedMGkUloIgpbMHm/n8oUNcyvAToTy2dYukEUwwh/IWOgcuztnm/jxPwf0rjLo7D6+N/cZDkQg==",
      "size": 87813794
    }
  }
]
```

Then after clicking "OK", I see the same as OP:
```
Please let us know of the following error message as it could be a bug:

abort({"code":"ERR_UPDATER_ZIP_FILE_NOT_FOUND"}) at Error
    at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11630)
    at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11801)
    at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:560006)
    at process.emit (events.js:203:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)
```

I've switched off automatic updates to see if that stops the dialogs from appearing.

**Comment by devinpearson** [comment]
@Drarok Im adding in the Mas build now that has the missing zip that it is looking for. 

I might switch 1.1.16 back to a prerelease as I believe it is causing the auto-updater script to run in the first place

**Comment by karlbuys** [comment]
@Drarok the latest 1.16 build has been released. 

Could you please turn auto-updates back on and let us know if you encounter any issues?

I'm going to mark this problem as closed for the time being, this problem should be resolved now that 1.16 has been released. Feel free to reopen it if you continue to experience the issue.

**Comment by Drarok** [comment]
Still broken for me:
```ZIP file not provided: [
  {
    "url": "https://github.com/mymonero/mymonero-app-js/releases/download/v1.1.16/MyMonero-1.1.16.dmg",
    "info": {
      "url": "MyMonero-1.1.16.dmg",
      "sha512": "1GAe0hg05mjbIfnjR86MN4j+sE4jftfeL+xMu0VQC3g8Sv766/P1oPOumoT4awZiRSc+HEHfYV222uyZw4RAhA==",
      "size": 87751320
    }
  }
]```

**Comment by Drarok** [comment]
@karlbuys I don't appear to have permission to re-open this issue, sadly.

**Comment by devinpearson** [comment]
@Drarok ive reopened the issue for you.

Are you on one of the beta builds. 

I found that our auto updated has been customized and does not seem to handling the channels correctly so the beta builds should only be updating to newer betas and not stable releases. However the client seems to still pickup the other channel releases and fails to download them correctly. 

If you can remove the app and install the new version it should work.

**Comment by Drarok** [comment]
I'm not on a beta, no:
![Screenshot 2020-10-19 at 15 15 04](https://user-images.githubusercontent.com/55830/96463435-a0bd2000-121e-11eb-95df-b3c8f964a7e2.png)

I'm sure if I manually update to 1.1.16 manually it'll work, up until the next release fails to find a ZIP file – unless changes have been made to the auto-update client since 1.1.13?

**Comment by Drarok** [comment]
Updated to 1.1.16 yesterday, now I get this! 😬 

```
Please let us know of the following error message as it could be a bug:

abort(Error: ZIP file not provided: [
  {
    "url": "https://github.com/mymonero/mymonero-app-js/releases/download/v1.1.17/MyMonero-1.1.17.dmg",
    "info": {
      "url": "MyMonero-1.1.17.dmg",
      "sha512": "RqLQrx1mDsqW/cowpOtS4UqNrd2sAFsKiP5NisaNkzj3TIGrZgPNwSi4+mhI48HncshCp2WSrc5p4UxC805GdQ==",
      "size": 87759660
    }
  }
]) at Error
    at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:27616)
    at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:27787)
    at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:20600)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by devinpearson** [comment]
Ive just pushed out v1.1.18 I believe it will fit this. its required that we build an additional step for the zip files that it uses to download the update. Ive tested it and so far it is working.

**Comment by Drarok** [comment]
Success!

![Screenshot 2020-10-20 at 13 25 26](https://user-images.githubusercontent.com/55830/96585627-c2c6a900-12d7-11eb-9d63-fbf2180763bc.png)

![Screenshot 2020-10-20 at 13 25 35](https://user-images.githubusercontent.com/55830/96585645-c8bc8a00-12d7-11eb-97d3-e2b61e872868.png)

**Comment by devinpearson** [comment]
Glad to hear you are sorted.

Thanks for being patient
