### ISSUE TITLE
Zip File Not Found Error

### ISSUE THREAD

**Issue by manlyman07** [mymonero/mymonero-app-js#317]
Error appearing in version 1.1.13. I'm running the MyMonero app on an iMac - MacOSX 10.13.6

"""
Please let us know of the following error message as it could be a bug:

abort({"code":"ERR_UPDATER_ZIP_FILE_NOT_FOUND"}) at Error
    at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11630)
    at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11801)
    at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:560006)
    at process.emit (events.js:203:13)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:86:32)

"""
Thanks,
Dane

**Comment by Drarok** [comment]
Isn't this the same as [the issue at the top of the list](https://github.com/mymonero/mymonero-app-js/issues/316) before you created yours?

**Comment by manlyman07** [comment]
Yes, apologies missed it. Closing this one.
