### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by ecols33** [mymonero/mymonero-app-js#320]
I can't tell what causes this error, but it's popped up around 5 times, while MyMonero was in the background.
MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) (MacBookPro15,2)
macOS Catalina 10.15.6
MyMonero version 1.1.16-beta. 

> abort({}) at Error
at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11630)
at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11801)
at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:560006)
at process.emit (events.js:210:5)
at processPromiseRejections (internal/process/promises.js:201:33)
at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by karlbuys** [comment]
@ecols33 Did you experience this problem with version 1.1.13 as well? Or only since you've updated to 1.1.16-beta?

**Comment by devinpearson** [comment]
We have found this error to be caused by having version 1.1.13 still installed on the machine when using the newer versions
