### ISSUE TITLE
Update Error - abort({}) at Error at jsStackTrace when opening the app

### ISSUE THREAD

**Issue by Bianca2112** [mymonero/mymonero-app-js#323]
User  is receiving this error when opening the app - he is using the latest version 

abort({}) at Error
at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11630)
at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:11801)
at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:560006)
at process.emit (events.js:210:5)
at processPromiseRejections (internal/process/promises.js:201:33)
at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by AncientSion** [comment]
I have the same issue. w10.

**Comment by parmen1** [comment]
same issue! Solution?

**Comment by parmen1** [comment]
Hi community,

following issue. Before few days i used Mymonero without issues.
Now since few Days, i cant receive my monero on 1.1.18 (newest Version) an older version diesnt work too. I get the error "error fetching mymonero updates" day before all works, now this big error https://prnt.sc/vwgtzm , i cant open the wallet on webwallet because lost my seed, how i can repair it? Have access to the wallet, but before i get this error message and the wallet dont synchronisate.

Is it possible to look my seed in MyMonero Account, with my Password? Thank you for help!

kidn regards
