### ISSUE TITLE
App on Mac OS giving this error

### ISSUE THREAD

**Issue by krisp1** [mymonero/mymonero-app-js#372]
Error msg told me to submit bug so here it is:

abort(Error: net::ERR_NETWORK_CHANGED) at Error
    at jsStackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:27616)
    at stackTrace (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:27787)
    at process.abort (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/mymonero_libapp_js/libapp_js/MyMoneroLibAppCpp_WASM.js:8:20600)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

**Comment by devinpearson** [comment]
We Will see if we can suppress these error messages. they usually happen when the computers gone to sleep or loss of internet connection for awhile.
