### ISSUE TITLE
Type Error: Cannot read property "length" of undefined.

### ISSUE THREAD

**Issue by hfun77** [mymonero/mymonero-app-js#411]
I got this error on macOS when I try to create a new wallet.
Once I get to the page that tells you about your Mnemonic, I click "Got It!", then next, then the error message appears.

<img width="612" alt="Screen Shot 2021-07-24 at 6 42 52 PM" src="https://user-images.githubusercontent.com/31161022/126883443-ba523d23-35c4-4225-b3cf-df84a1a726b7.png">

I can try clicking the next button again, but this time it jumps directly to the "verify you know your Mnemonic" page, which is completely useless as it has not given it to me yet.

**Here is the full text in the error bubble in case you need it:**

An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:

TypeError: Cannot read property 'length' of undefined

TypeError: Cannot read property 'length' of undefined
at CreateWallet_InformOfMnemonic_View._setup_form_field_language (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Views/CreateWallet_InformOfMnemonic_View.web.js:113:34)
at CreateWallet_InformOfMnemonic_View._setup_views (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Views/CreateWallet_InformOfMnemonic_View.web.js:85:8)
at CreateWallet_InformOfMnemonic_View.setup (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Views/BaseView_AWalletWizardScreen.web.js:51:8)
at new AddWallet_LandingScreenView (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Views/BaseView_AWalletWizardScreen.web.js:46:8)
at new CreateWallet_InformOfMnemonic_View (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Views/CreateWallet_InformOfMnemonic_View.web.js:37:1)
at AddWallet_WizardController._new_current_wizardTaskMode_stepView (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Controllers/AddWallet_WizardController.web.js:193:23)
at AddWallet_WizardController.ProceedToNextStep (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Controllers/AddWallet_WizardController.web.js:276:25)
at /Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Views/CreateWallet_Instructions_View.web.js:307:27
at /Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletWizard/Controllers/AddWallet_WizardController.web.js:321:6
at successfullyInitialized_cb (/Applications/MyMonero.app/Contents/Resources/app.asar/local_modules/WalletsList/Controllers/WalletsListController.js:215:5)

**Comment by devinpearson** [comment]
Hi there. Can you confirm if you are experiencing this issue on v1.1.24

**Comment by hfun77** [comment]
Yes, here is the screenshot from the version window.
<img width="312" alt="Screen Shot 2021-07-25 at 7 46 45 AM" src="https://user-images.githubusercontent.com/31161022/126899482-e4b35fda-f2b7-44a9-83ae-63fa0030ff63.png">

**Comment by karlbuys** [comment]
This issue is fixed in MyMonero 1.2.0 and above
