### ISSUE TITLE
RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by proudmuslim-dev** [mymonero/mymonero-app-js#426]
### Description

Constantly spamming error window

- [ ] Can you reproduce the issue? 

### Steps to reproduce

1. Open MyMonero
2. Wait a little bit

**Expected behavior:**

Expected the app to function normally

**Actual behavior:**

Notifications on my screen every 30 or so seconds

**Link to an example: [optional]**
![image](https://user-images.githubusercontent.com/69869443/137595670-5a54b29d-b5a1-4059-ac16-d11fb2a34428.png)

### Versions

- Operating system: Arch Linux

**Comment by karlbuys** [comment]
Hi there

Apologies for the slow response.

That error has to do with the wallet attempting to display a transaction's date in your local timezone. My suspicion is that your timezone and/or locale have not been set up.

Please check to see that your locale and timezone are set properly.

In /etc/locale.conf, you should see two strings that looks like the following: 

LC_TIME=en_GB.UTF-8
LANG=en_GB.UTF-8

If those lines aren't there, please follow the steps at https://wiki.archlinux.org/title/locale#Setting_the_locale and let us know if you continue to have issues

**Comment by proudmuslim-dev** [comment]
Hi! It turns out that you are correct, I don't have `LC_TIME` set
![image](https://user-images.githubusercontent.com/69869443/140777387-27cb2b28-635f-47d6-830d-60fb99c9e46c.png)

Apologies for bothering you guys, I'll set the variable and close this after some testing

**Comment by proudmuslim-dev** [comment]
Update: the issue persists

![image](https://user-images.githubusercontent.com/69869443/140984577-226729fc-72d6-47d2-b4fc-3ae579c7b6a9.png)

![image](https://user-images.githubusercontent.com/69869443/140984649-fcf0bf01-ff88-4626-a738-74a79a1456ba.png)
![image](https://user-images.githubusercontent.com/69869443/140984684-fee3da0b-3f43-4d4d-afc8-3cf7e6467685.png)

**Comment by karlbuys** [comment]
Could you check to see if "en_US.UTF-8 UTF-8" is uncommented in /etc/locale.gen please?

If it is, remove the # before it. See below for example:

#en_SG ISO-8859-1
en_US.UTF-8 UTF-8
#en_US ISO-8859-1

Then, run locale-gen

Please let me know if this sorts the issue out.

**Comment by proudmuslim-dev** [comment]
Yes, it's uncommented as I did it during the installation process
![image](https://user-images.githubusercontent.com/69869443/141488040-3cce545c-4663-42b9-9baa-b35259e055af.png)

**Comment by karlbuys** [comment]
I've been looking at the code causing the issue. I suspect that the problem is due to two reasons. I believe Arch Linux is using non-standard locale codes. en-US is a valid locale code according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString.

When we're unable to determine the user's locale, we were falling back to 'en-US'. A better solution is to specify the locale as the type 'undefined', which will use the system's default provided locale.

**Comment by JohnnyKarate2** [comment]
Will this issue be fixed sometime soon? I can't access my wallet right now

**Comment by Clausinho** [comment]
> Will this issue be fixed sometime soon? I can't access my wallet right now
I am experiencing the same issue on arch linux. I can however click it away and use my wallet, even though it is quite tedious. 

Is there a way to just mute these errors, as they don't seem to impair any features apart from sending annoying error alerts.

**Comment by JohnnyKarate2** [comment]
Awesome, thanks!

**Comment by storopoli** [comment]
I am still seeing this in Arch Linux using version 1.2.4:

```bash
❯ cat /etc/locale.conf
LANG=en_US.UTF-8
LC_TIME=en_US.UTF-8
```

**Comment by vivyir** [comment]
I am also seeing this error, not particularly fond of changing my whole system's language to English, maybe adding a fallback mechanism to the app would be better?

**Comment by AndreiBiziuk** [comment]
After update to v1.3.3-2 receive this error every time when click on wallet with transactions.

```
An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:

 <p><span style='font-size: 11px;'>RangeError: Incorrect locale information provided</span></p>RangeError: Incorrect locale information provided
    at Date.toLocaleDateString (<anonymous>)
    at /opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:883:37
    at Array.forEach (<anonymous>)
    at WalletDetailsView._configureUIWithWallet__transactions (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:816:31)
    at WalletDetailsView.setup (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:44:10)
    at new WalletDetailsView (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:29:10)
    at WalletsListView.pushRecordDetailsView (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:232:20)
    at WalletsListView.cellWasTapped (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:251:12)
    at WalletsListCellView.cell_tapped_fn (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:186:15)
    at /opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListCellView.web.js:96:14Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) MyMonero/1.3.3 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36
```
Previously there was no errors.

my locale is `ru_RU.UTF-8`

OS: Arch Linux

**Comment by amusingaxl** [comment]
Same issue here on Manjaro.
When I installed the AppImage standalone, I didn't see this issue, but then I removed it and used the AUR package, which caused the error to appear.
I'd like to use the AUR package because of the automatic updates.

```
An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:


 <p><span style='font-size: 11px;'>RangeError: Incorrect locale information provided</span></p>RangeError: Incorrect locale information provided
    at Date.toLocaleDateString (<anonymous>)
    at /opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:883:37
    at Array.forEach (<anonymous>)
    at WalletDetailsView._configureUIWithWallet__transactions (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:816:31)
    at WalletDetailsView.setup (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:44:10)
    at new WalletDetailsView (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:29:10)
    at WalletsListView.pushRecordDetailsView (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:232:20)
    at WalletsListView.cellWasTapped (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:251:12)
    at WalletsListCellView.cell_tapped_fn (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:186:15)
    at /opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListCellView.web.js:96:14Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) MyMonero/1.3.3 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36
```

**Comment by SunilPaul174** [comment]
An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:

 <p><span style='font-size: 11px;'>RangeError: Incorrect locale information provided</span></p>RangeError: Incorrect locale information provided
    at Date.toLocaleDateString (<anonymous>)
    at /opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:883:37
    at Array.forEach (<anonymous>)
    at WalletDetailsView._configureUIWithWallet__transactions (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:816:31)
    at WalletDetailsView.setup (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:44:10)
    at new WalletDetailsView (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:29:10)
    at WalletsListView.pushRecordDetailsView (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:232:20)
    at WalletsListView.cellWasTapped (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:251:12)
    at WalletsListCellView.cell_tapped_fn (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:186:15)
    at /opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListCellView.web.js:96:14Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) MyMonero/1.3.3 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36
    
    Still having this issue on 
![image](https://github.com/user-attachments/assets/ab8cb1d7-4066-4384-b16d-da6fb446ba51)

**Comment by r3k2** [comment]
Having this same error on Arch GNU/Linux this used to work last year or so.
```
An unexpected application error occurred.

Please let us know of the following error message as it could be a bug:

 <p><span style='font-size: 11px;'>RangeError: Incorrect locale information provided</span></p>RangeError: Incorrect locale information provided
    at Date.toLocaleDateString (<anonymous>)
    at /opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:883:37
    at Array.forEach (<anonymous>)
    at WalletDetailsView._configureUIWithWallet__transactions (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:816:31)
    at WalletDetailsView.setup (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:44:10)
    at new WalletDetailsView (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:29:10)
    at WalletsListView.pushRecordDetailsView (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:232:20)
    at WalletsListView.cellWasTapped (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:251:12)
    at WalletsListCellView.cell_tapped_fn (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:186:15)
    at /opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListCellView.web.js:96:14Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) MyMonero/1.3.3 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36
    ```
    ```
    cat /etc/locale.conf 
LANG=en_US.UTF-8
```
i also tried passing the LANG= variable to mymonero same problem :(

**Comment by darash** [comment]
ArchLinux

```
 <p><span style='font-size: 11px;'>RangeError: Incorrect locale information provided</span></p>RangeError: Incorrect locale information provided
    at Date.toLocaleDateString (<anonymous>)
    at /opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:883:37
    at Array.forEach (<anonymous>)
    at WalletDetailsView._configureUIWithWallet__transactions (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:816:31)
    at WalletDetailsView.setup (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:44:10)
    at new WalletDetailsView (/opt/mymonero/resources/app.asar/local_modules/Wallets/Views/WalletDetailsView.web.js:29:10)
    at WalletsListView.pushRecordDetailsView (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:232:20)
    at WalletsListView.cellWasTapped (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:251:12)
    at WalletsListCellView.cell_tapped_fn (/opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListView.web.js:186:15)
    at /opt/mymonero/resources/app.asar/local_modules/Lists/Views/ListCellView.web.js:96:14Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) MyMonero/1.3.3 Chrome/83.0.4103.122 Electron/9.4.4 Safari/537.36
```

/usr/bin/mymonero

```
Warning: require() of ES modules is not supported.
require() of /opt/mymonero/resources/app.asar/node_modules/lit/index.js from /opt/mymonero/resources/app.asar/node_modules/@mymonero/mymonero-web-components/lib/Components/Shared/ActivityIndicator.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /opt/mymonero/resources/app.asar/node_modules/lit/package.json.
```
