### ISSUE TITLE
Possibly with introduction of auto db compaction, NeDB is now liable to leave the db in a corrupt state when user quits app, say, after changing PW

### ISSUE THREAD

**Issue by paulshapiro** [mymonero/mymonero-app-js#91]
Just experienced this while testing PW change and then quickly quitting the app.

```
mymonero-app/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (mymonero-app/node_modules/nedb/lib/persistence.js:242:11)
    at mymonero-app/node_modules/nedb/lib/persistence.js:281:38
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
```

Found unsolved NeDB issue and commented with potential cause. Awaiting maintainer reply. https://github.com/louischatriot/nedb/issues/455

Possible solutions:
* Setting autocompaction interval from 60s to something more like 1s to make likelihood of quit/crash during compaction much lower
* Doing compaction manually on writes, incrementing counter, listening for done to decrement counter, and delaying app quit until that counter is back to 0 -- this is probably suboptimal though because we probably can't do that on mobile, and the app could be quit anytime on mobile. (Good thing we'll have Realm in the native apps.)

**Comment by paulshapiro** [comment]
It looks like a re-launch left it in a workable state - probably the datastore load triggers an autocompaction, and autocompactions remove corrupted records (although I'm not clear on whether there would be dataloss in that case). 

So, another possible solution (at least, if there is no dataloss on a corruption..?) would be to attempt to load the DB again in case of errors, maybe with some limit on number of retries.

**Comment by paulshapiro** [comment]
Looks like NeDB writes / syncs happen somewhat in the background after a write call's cb is called. Just something to keep in mind.

**Comment by paulshapiro** [comment]
Implemented the above two things. Closing this one for now. Might be worth re-opening if we are seeing actual dataloss in normal use cases and want to switch to another db or follow up.

**Comment by paulshapiro** [comment]
Just got this again :\ So, re-opening.

**Comment by paulshapiro** [comment]
Dang, saw it again. Probably will switch away from NeDB.

**Comment by paulshapiro** [comment]
I added commits https://github.com/mymonero/mymonero-app-js/commit/67a1d58bbe8c1384ff3584a63b1efd66dd8d10e0 and https://github.com/mymonero/mymonero-app-js/commit/ef9c843c13aa01147057913f3e175cd353081fb4 to fix the apparent mistake in error detection in previous attempt at ability to recover on launch from failed datastore load on corrupted db. I have yet to be able to verify this as a fix to datastore load err detection because I've not yet been able to reproduce a database corruption event. Stay tuned.

Other db options I'm considering are leveldb and sqlite. If I really do need to change the db out, it would probably be much better to do it before the public launch. So I'm going to put the blocking label back on this issue.

**Comment by paulshapiro** [comment]
Related (trivial): https://github.com/mymonero/mymonero-app-js/commit/9902063dd6458b2e26f12bb9d614a950302c3109

**Comment by paulshapiro** [comment]
Fixed by https://github.com/mymonero/mymonero-app-js/commit/8fb7bb07bf77fb0a0af2dcb24754d8ecfde79024
